[package]
name = "linear-models"
version = "0.1.0"
authors = ["Dan Crankshaw <dscrankshaw@gmail.com>"]

[lib]
name = "linear_models"
path = "src/lib.rs"

[dependencies]
libc = "0.1.8"
rand = "0.3"
threadpool = "0.1"
time = "0.1"
